"""no_schema_changes

Revision ID: 9d9e0f2d796a
Revises: 89f9783a2b2c
Create Date: 2026-06-18 18:43:10.755312

All autogenerated diffs are SQLite type-representation noise (SQLite
stores Boolean as INTEGER, String as TEXT, etc.).  No real schema
changes were made — this revision just advances the Alembic version
chain so future migrations have the correct down_revision.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d9e0f2d796a'
down_revision: Union[str, Sequence[str], None] = '89f9783a2b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
