"""baseline

Revision ID: cd25f9429f6e
Revises: 
Create Date: 2026-06-16 21:14:54.036780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd25f9429f6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_movements')
    op.drop_table('purchase_orders')
    op.drop_table('materials')
    op.drop_table('material_requests')
    op.drop_table('purchase_order_items')
    op.alter_column('checklist_assignments', 'evidence_required',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('checklist_assignments', 'is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('checklist_templates', 'evidence_required',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('fms_stage_history', 'evidence_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('fms_stage_history', 'evidence_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('fms_stages', 'evidence_required',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('library_flow_stages', 'evidence_required',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('tenant_label_configs', 'store_manager_s')
    op.drop_column('tenant_label_configs', 'inventory_s')
    op.drop_column('tenant_label_configs', 'purchase_order_p')
    op.drop_column('tenant_label_configs', 'supplier_s')
    op.drop_column('tenant_label_configs', 'stock_out_s')
    op.drop_column('tenant_label_configs', 'purchase_order_s')
    op.drop_column('tenant_label_configs', 'supplier_p')
    op.drop_column('tenant_label_configs', 'material_s')
    op.drop_column('tenant_label_configs', 'store_manager_p')
    op.drop_column('tenant_label_configs', 'inventory_p')
    op.drop_column('tenant_label_configs', 'adjustment_s')
    op.drop_column('tenant_label_configs', 'stock_in_s')
    op.drop_column('tenant_label_configs', 'material_p')
    op.alter_column('tenants', 'checklist_notif_hours',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tickets', 'ticket_category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tickets', 'evidence_required',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('users', 'branch_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'employee_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'joining_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'terminated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'terminated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'joining_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'employee_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'branch_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tickets', 'evidence_required',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tickets', 'ticket_category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tenants', 'checklist_notif_hours',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('tenant_label_configs', sa.Column('material_p', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('stock_in_s', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('adjustment_s', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('inventory_p', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('store_manager_p', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('material_s', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('supplier_p', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('purchase_order_s', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('stock_out_s', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('supplier_s', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('purchase_order_p', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('inventory_s', sa.VARCHAR(), nullable=True))
    op.add_column('tenant_label_configs', sa.Column('store_manager_s', sa.VARCHAR(), nullable=True))
    op.alter_column('library_flow_stages', 'evidence_required',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fms_stages', 'evidence_required',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fms_stage_history', 'evidence_filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('fms_stage_history', 'evidence_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('checklist_templates', 'evidence_required',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('checklist_assignments', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('checklist_assignments', 'evidence_required',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('po_id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('material_id', sa.VARCHAR(), nullable=True),
    sa.Column('material_name', sa.VARCHAR(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('qty_ordered', sa.FLOAT(), nullable=False),
    sa.Column('qty_received', sa.FLOAT(), nullable=True),
    sa.Column('unit_cost', sa.FLOAT(), nullable=True),
    sa.Column('total_cost', sa.FLOAT(), nullable=True),
    sa.Column('is_fully_received', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_requests',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('ticket_id', sa.VARCHAR(), nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('material_id', sa.VARCHAR(), nullable=True),
    sa.Column('material_name', sa.VARCHAR(), nullable=True),
    sa.Column('qty_requested', sa.INTEGER(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('approved_by_id', sa.VARCHAR(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('rejection_note', sa.TEXT(), nullable=True),
    sa.Column('fulfilled_qty', sa.INTEGER(), nullable=True),
    sa.Column('fulfilled_at', sa.DATETIME(), nullable=True),
    sa.Column('requested_by_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('stage_id', sa.VARCHAR(), nullable=True),
    sa.Column('stage_name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['fms_stages.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['fms_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('reorder_threshold', sa.INTEGER(), nullable=True),
    sa.Column('reorder_qty', sa.INTEGER(), nullable=True),
    sa.Column('lead_time_days', sa.INTEGER(), nullable=True),
    sa.Column('supplier', sa.VARCHAR(), nullable=True),
    sa.Column('opening_stock', sa.INTEGER(), nullable=True),
    sa.Column('current_stock', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('branch_id', sa.VARCHAR(), nullable=True),
    sa.Column('department_id', sa.VARCHAR(), nullable=True),
    sa.Column('po_number', sa.VARCHAR(), nullable=False),
    sa.Column('supplier', sa.VARCHAR(), nullable=True),
    sa.Column('supplier_ref', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('expected_delivery', sa.DATE(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by_id', sa.VARCHAR(), nullable=False),
    sa.Column('approved_by_id', sa.VARCHAR(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('received_at', sa.DATETIME(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('cancel_reason', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('material_id', sa.VARCHAR(), nullable=False),
    sa.Column('branch_id', sa.VARCHAR(), nullable=True),
    sa.Column('department_id', sa.VARCHAR(), nullable=True),
    sa.Column('movement_type', sa.VARCHAR(), nullable=False),
    sa.Column('qty', sa.FLOAT(), nullable=False),
    sa.Column('qty_before', sa.FLOAT(), nullable=False),
    sa.Column('qty_after', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('unit_cost', sa.FLOAT(), nullable=True),
    sa.Column('total_cost', sa.FLOAT(), nullable=True),
    sa.Column('reference', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('po_item_id', sa.VARCHAR(), nullable=True),
    sa.Column('actor_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['po_item_id'], ['purchase_order_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
