"""gupshup_multitenant

Revision ID: d84d69ded1cc
Revises: gr0up1ngdup2
Create Date: 2026-07-13 21:32:21.772422

Pruned by hand from the autogenerated diff: SQLite reflection reported a large
number of unrelated type/FK/index drift across the schema (pre-existing,
not caused by this change) — only the columns/table actually introduced by
the Gupshup migration brief are included here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84d69ded1cc'
down_revision: Union[str, Sequence[str], None] = 'gr0up1ngdup2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('whatsapp_consent_events',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('employee_id', sa.String(), nullable=True),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(), nullable=False),
        sa.Column('gupshup_message_id', sa.String(), nullable=True),
        sa.Column('raw_webhook_payload', sa.JSON(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('actor_id', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gupshup_client_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gupshup_secret_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gupshup_source_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gupshup_waba_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gupshup_webhook_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gupshup_webhook_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_opt_in_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_config_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_tenants_gupshup_webhook_token', ['gupshup_webhook_token'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_opt_in_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('opt_in_source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('opt_in_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('matched_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mismatch_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('opt_in_actor_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_users_opt_in_actor_id', 'users', ['opt_in_actor_id'], ['id'])

    with op.batch_alter_table('whatsapp_message_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('template_category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('delivery_status_history', sa.JSON(), nullable=True, server_default='[]'))
        batch_op.add_column(sa.Column('raw_status_webhook_payloads', sa.JSON(), nullable=True, server_default='[]'))

    # Backfill existing rows' opt-in status from the legacy mobile_verified boolean,
    # then default remaining PENDING for any not yet set.
    op.execute("UPDATE users SET whatsapp_opt_in_status = 'MANUALLY_VERIFIED' WHERE mobile_verified = 1")
    op.execute("UPDATE users SET whatsapp_opt_in_status = 'PENDING' WHERE whatsapp_opt_in_status IS NULL")
    op.execute("UPDATE tenants SET gupshup_waba_status = 'PENDING' WHERE gupshup_waba_status IS NULL")
    op.execute("UPDATE whatsapp_message_log SET delivery_status_history = '[]' WHERE delivery_status_history IS NULL")
    op.execute("UPDATE whatsapp_message_log SET raw_status_webhook_payloads = '[]' WHERE raw_status_webhook_payloads IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('whatsapp_message_log', schema=None) as batch_op:
        batch_op.drop_column('raw_status_webhook_payloads')
        batch_op.drop_column('delivery_status_history')
        batch_op.drop_column('template_category')
        batch_op.drop_column('template_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_opt_in_actor_id', type_='foreignkey')
        batch_op.drop_column('opt_in_actor_id')
        batch_op.drop_column('mismatch_reason')
        batch_op.drop_column('matched_phone')
        batch_op.drop_column('opt_in_at')
        batch_op.drop_column('opt_in_source')
        batch_op.drop_column('whatsapp_opt_in_status')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tenants_gupshup_webhook_token', type_='unique')
        batch_op.drop_column('whatsapp_config_updated_at')
        batch_op.drop_column('whatsapp_opt_in_link')
        batch_op.drop_column('gupshup_webhook_secret')
        batch_op.drop_column('gupshup_webhook_token')
        batch_op.drop_column('gupshup_waba_status')
        batch_op.drop_column('gupshup_source_number')
        batch_op.drop_column('gupshup_secret_token')
        batch_op.drop_column('gupshup_client_id')

    op.drop_table('whatsapp_consent_events')
